name: Release Dispatch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.0.0)'
        required: true
        type: string
      dry_run:
        description: 'Dry run (no actual release)'
        required: false
        type: boolean
        default: false

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch release workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release
          client-payload: '{"version": "${{ github.event.inputs.version }}", "dry_run": ${{ github.event.inputs.dry_run }}}'
